Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.ComponentModel

Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

        Public Overrides ReadOnly Property Context As SettingsContext
            Get
                Return MyBase.Context
            End Get
        End Property

        Public Overrides ReadOnly Property Properties As SettingsPropertyCollection
            Get
                Return MyBase.Properties
            End Get
        End Property

        Public Overrides ReadOnly Property PropertyValues As SettingsPropertyValueCollection
            Get
                Return MyBase.PropertyValues
            End Get
        End Property

        Public Overrides ReadOnly Property Providers As SettingsProviderCollection
            Get
                Return MyBase.Providers
            End Get
        End Property

        Default Public Overrides Property Item(propertyName As String) As Object
            Get
                Return MyBase.Item(propertyName)
            End Get
            Set(value As Object)
                MyBase.Item(propertyName) = value
            End Set
        End Property

        Public Overrides Sub Save()
            MyBase.Save()
        End Sub

        Public Overrides Sub Upgrade()
            MyBase.Upgrade()
        End Sub

        Protected Overrides Sub Finalize()
            MyBase.Finalize()
        End Sub

        Protected Overrides Sub OnPropertyChanged(sender As Object, e As PropertyChangedEventArgs)
            MyBase.OnPropertyChanged(sender, e)
        End Sub

        Protected Overrides Sub OnSettingChanging(sender As Object, e As SettingChangingEventArgs)
            MyBase.OnSettingChanging(sender, e)
        End Sub

        Protected Overrides Sub OnSettingsLoaded(sender As Object, e As SettingsLoadedEventArgs)
            MyBase.OnSettingsLoaded(sender, e)
        End Sub

        Protected Overrides Sub OnSettingsSaving(sender As Object, e As CancelEventArgs)
            MyBase.OnSettingsSaving(sender, e)
        End Sub

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared Function GetDefault() As MySettings

#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Function

        Public Overrides Function Equals(obj As Object) As Boolean
            Return MyBase.Equals(obj)
        End Function

        Public Overrides Function GetHashCode() As Integer
            Return MyBase.GetHashCode()
        End Function

        Public Overrides Function ToString() As String
            Return MyBase.ToString()
        End Function
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.ASCOM.TEMPLATEDEVICENAME.My.MySettings
            Get
                Return Global.ASCOM.TEMPLATEDEVICENAME.My.MySettings.GetDefault()
            End Get
        End Property
    End Module
End Namespace
