<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net472</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>
	<PropertyGroup>
	    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>

		<ProductVersion>8.0.50727</ProductVersion>
		<AssemblyName>DynamicClientServer</AssemblyName>
		<IsWebBootstrapper>false</IsWebBootstrapper>
		<PublishUrl>publish\</PublishUrl>
		<Install>true</Install>
		<InstallFrom>Disk</InstallFrom>
		<UpdateEnabled>false</UpdateEnabled>
		<UpdateMode>Foreground</UpdateMode>
		<UpdateInterval>7</UpdateInterval>
		<UpdateIntervalUnits>Days</UpdateIntervalUnits>
		<UpdatePeriodically>false</UpdatePeriodically>
		<UpdateRequired>false</UpdateRequired>
		<MapFileExtensions>true</MapFileExtensions>
		<ApplicationRevision>0</ApplicationRevision>
		<ApplicationVersion>1.0.0.%2a</ApplicationVersion>
		<UseApplicationTrust>false</UseApplicationTrust>
		<BootstrapperEnabled>true</BootstrapperEnabled>
		<AssemblyTitle>ASCOM.AlpacaSim.LocalServer</AssemblyTitle>
		<Company>The ASCOM Initiative</Company>
		<Product>Alpaca Simulators Local Server</Product>
		<Description>ASCOM Local Server for Alpaca Simulators</Description>
		<Copyright>Copyright © The ASCOM Initiative 2025</Copyright>
		<AssemblyVersion>7.0.0.0</AssemblyVersion>
		<FileVersion>7.0.0.0</FileVersion>
	</PropertyGroup>


<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <OutputPath>bin\$(Configuration)\$(Platform)\</OutputPath>
    <PlatformTarget>$(Platform)</PlatformTarget>
    <DocumentationFile>bin\$(Configuration)\$(Platform)\ASCOM.Astrometry.xml</DocumentationFile>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)' == 'Release'">
     <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\$(Configuration)\$(Platform)\</OutputPath>
    <PlatformTarget>$(Platform)</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <CodeAnalysisRuleSet>..\..\Ascom.ruleset</CodeAnalysisRuleSet>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <DefineConstants>TRACE</DefineConstants>
</PropertyGroup>  




	<PropertyGroup>
		<SignAssembly>true</SignAssembly>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyOriginatorKeyFile>LocalServer.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<PropertyGroup>
		<PreBuildEvent />
		<PostBuildEvent />
		<RootNamespace>ASCOM.DynamicClients</RootNamespace>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Include="ASCOM.ico" />
		<Content Include="ASCOM.png" />
	</ItemGroup>
	<ItemGroup>
		<None Include="LocalServer.snk" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="ASCOM.Alpaca.Components" Version="2.2.0" />
	  <PackageReference Include="ASCOM.Com.Components" Version="2.2.0" />
	  <PackageReference Include="ASCOM.Common.Components" Version="2.2.0" />
	  <PackageReference Include="ASCOM.Tools" Version="2.2.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\ASCOM.DeviceInterface\ASCOM.DeviceInterface.csproj" />
	  <ProjectReference Include="..\..\..\ASCOM.Exceptions\ASCOM.Exceptions.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="System.Security" />
	</ItemGroup>
	   <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>