<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ASCOM.DeviceHub</RootNamespace>
    <AssemblyName>ASCOM.DeviceHub</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Images\ASCOM.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>ASCOM.snk</AssemblyOriginatorKeyFile>
    <NoWin32Manifest>true</NoWin32Manifest>
  </PropertyGroup>

  <ItemGroup>
    <None Include="ASCOM.snk" />
    <None Include="TelescopeControlClasses.cd" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\icon down arrow.png" />
    <Resource Include="Images\icon rotate left.png" />
    <Resource Include="Images\icon rotate right.png" />
    <Resource Include="Images\icon up arrow.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\ASCOM.ico" />
    <Resource Include="Images\Stop.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\ASCOM.Astrometry\ASCOM.Astrometry\ASCOM.Astrometry.csproj">
      <Project>{0EC4FAEB-5265-0C28-3C03-9AAF43433A73}</Project>
      <Name>ASCOM.Astrometry</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\ASCOM.Attributes\ASCOM.Attributes.csproj">
      <Project>{2c40fad9-de75-4360-a0ad-911c4d24d98c}</Project>
      <Name>ASCOM.Attributes</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\ASCOM.DeviceInterface\ASCOM.DeviceInterface.csproj">
      <Project>{350a73bd-60d1-03e4-2edc-a617d2d79ce3}</Project>
      <Name>ASCOM.DeviceInterface</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\ASCOM.DriverAccess\ASCOM.DriverAccess.csproj">
      <Project>{3b6c23f5-c590-4385-86bb-98b604b565ba}</Project>
      <Name>ASCOM.DriverAccess</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\ASCOM.Exceptions\ASCOM.Exceptions.csproj">
      <Project>{6fd62ea4-8b79-4805-85ec-35178759c405}</Project>
      <Name>ASCOM.Exceptions</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\ASCOM.Utilities\ASCOM.Utilities\ASCOM.Utilities.csproj">
      <Project>{7B9B8BE0-9517-0548-11D2-27B6261AB180}</Project>
      <Name>ASCOM.Utilities</Name>
    </ProjectReference>
    <ProjectReference Include="..\MvvmMessenger\MvvmMessenger.csproj">
      <Project>{3c199a36-99a6-4c99-bab3-e37a81505111}</Project>
      <Name>MvvmMessenger</Name>
    </ProjectReference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&quot;$(SolutionDir)installercopy.cmd&quot; &quot;$(SolutionDir)&quot; &quot;$(TargetDir)$(TargetName).*&quot;" />
  </Target>
</Project>