<Project Sdk="Microsoft.NET.Sdk">
  <Target Name="VsixCompatibilityAnalyzer">
  </Target>
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <RunAnalyzers>false</RunAnalyzers>
    <DeployExtension>false</DeployExtension>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>ASCOMVsixTemplateInstaller</RootNamespace>
    <AssemblyName>ASCOMVsixTemplateInstaller</AssemblyName>
    <GeneratePkgDefFile>false</GeneratePkgDefFile>
    <IncludeAssemblyInVSIXContainer>false</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
    <StartAction>Program</StartAction>
    <StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
    <AssemblyTitle>ASCOM VSIX Template Installer %28VS2022%29</AssemblyTitle>
    <Product>ASCOMVsixTemplateInstaller</Product>
    <Copyright>2024 ASCOM Initiative</Copyright>
    <AssemblyVersion>7.0.0.0</AssemblyVersion>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers">
      <Version>3.3.4</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.CoreUtility">
      <Version>17.13.226</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.13.40008" ExcludeAssets="runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.SDK.Analyzers">
      <Version>17.7.47</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading">
      <Version>17.13.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers">
      <Version>17.13.2</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VsSDK.CompatibilityAnalyzer">
      <Version>17.13.2126</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Validation">
      <Version>17.8.8</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ASCOM.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="License.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="ReleaseNotes.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ASCOM.Setup.TemplateWizard2022\ASCOM.Setup.VsixWizard %28VS2022%29.csproj">
      <Project>{c809cc68-5e97-4c8e-9959-cf7cdea70e6f}</Project>
      <Name>ASCOM.Setup.VsixWizard %28VS2022%29</Name>
      <IncludeOutputGroupsInVSIX>BuiltProjectOutputGroup%3bBuiltProjectOutputGroupDependencies%3bGetCopyToOutputDirectoryItems%3bSatelliteDllsProjectOutputGroup%3b</IncludeOutputGroupsInVSIX>
      <IncludeOutputGroupsInVSIXLocalOnly>DebugSymbolsProjectOutputGroup%3b</IncludeOutputGroupsInVSIXLocalOnly>
    </ProjectReference>
    <ProjectReference Include="..\LocalServerTemplate\LocalServerTemplate.csproj">
      <Project>{F17A065B-EAD3-40D1-B6E4-5AC30BAC886F}</Project>
      <Name>LocalServerTemplate</Name>
      <VSIXSubPath>ProjectTemplates</VSIXSubPath>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup%3b</IncludeOutputGroupsInVSIX>
    </ProjectReference>
    <ProjectReference Include="..\TestConsoleApp%28CS%29\TestConsoleApp%28CS%29.csproj">
      <Project>{1D704121-F745-4734-B8B1-CD6866AF3AFA}</Project>
      <Name>TestConsoleApp%28CS%29</Name>
      <VSIXSubPath>ProjectTemplates</VSIXSubPath>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup%3b</IncludeOutputGroupsInVSIX>
    </ProjectReference>
    <ProjectReference Include="..\TestFormsApp%28CS%29\TestFormsApp%28CS%29.csproj">
      <Project>{DB7501D8-D922-49DA-B6AA-393E2CE03976}</Project>
      <Name>TestFormsApp%28CS%29</Name>
      <VSIXSubPath>ProjectTemplates</VSIXSubPath>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup%3b</IncludeOutputGroupsInVSIX>
    </ProjectReference>
  </ItemGroup>

  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
</Project>