<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ASCOM.Simulator</RootNamespace>
    <AssemblyName>ASCOM.Simulator.ObservingConditions</AssemblyName>
    <ApplicationIcon>ASCOM.ico</ApplicationIcon>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\ASCOM.snk</AssemblyOriginatorKeyFile>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.configuration" />
    <Reference Include="System.Configuration.Install" />
    <Reference Update="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Net" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ASCOM.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\ASCOM.Attributes\ASCOM.Attributes.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.DeviceInterface\ASCOM.DeviceInterface.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.DriverAccess\ASCOM.DriverAccess.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.Exceptions\ASCOM.Exceptions.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.Utilities\ASCOM.Utilities\ASCOM.Utilities.csproj" />
    <ProjectReference Include="..\OC Simulator Server\OC Simulator Server.csproj" />
  </ItemGroup>
  <PropertyGroup />
  <PropertyGroup>
    <PostBuildEvent>
      copy "$(TargetPath)" "$(SolutionDir)Drivers and Simulators\ObservingConditions Simulator\OC Simulator Server\$(OutDir)$(TargetFileName)"
      copy "$(SolutionDir)Drivers and Simulators\ObservingConditions Simulator\OC Simulator Driver\$(OutDir)ASCOM.Simulator.ObservingConditions.pdb" "$(SolutionDir)Drivers and Simulators\ObservingConditions Simulator\OC Simulator Server\$(OutDir)ASCOM.Simulator.ObservingConditions.pdb"
      copy "$(SolutionDir)Drivers and Simulators\ObservingConditions Simulator\OC Simulator Driver\$(OutDir)ASCOM.Simulator.ObservingConditions.dll.config" "$(SolutionDir)Drivers and Simulators\ObservingConditions Simulator\OC Simulator Server\$(OutDir)ASCOM.Simulator.ObservingConditions.dll.config"
    </PostBuildEvent>
    <AssemblyTitle>ASCOM ObservingConditions Simulator</AssemblyTitle>
    <Description>ASCOM Observing Conditions Simulator</Description>
    <Company>ASCOM Initiative</Company>
    <Product>ASCOM Observing Conditions Simulator</Product>
    <Copyright>Copyright © ASCOM Initiative 2024</Copyright>
    <AssemblyVersion>7.0.0.0</AssemblyVersion>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
</Project>