<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ASCOM.Simulator</RootNamespace>
    <AssemblyName>ASCOM.TelescopeSimulator</AssemblyName>
    <AssemblyOriginatorKeyFile>..\..\..\ASCOM.snk</AssemblyOriginatorKeyFile>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <PublishUrl>http://localhost/LocalServerCOM/</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>ASCOM.Simulator.TelescopeSimulator</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Ascom_Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\ASCOM.snk">
      <Link>ASCOM.snk</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <CodeAnalysisDictionary Include="..\..\..\CustomDictionary.xml">
      <Link>CustomDictionary.xml</Link>
    </CodeAnalysisDictionary>
    <Content Include="ASCOM.png" />
    <Content Include="ReadMe.htm" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\ASCOM.Astrometry\ASCOM.Astrometry\ASCOM.Astrometry.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.Attributes\ASCOM.Attributes.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.Controls\ASCOM.Controls\ASCOM.Controls.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.DeviceInterface\ASCOM.DeviceInterface.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.Exceptions\ASCOM.Exceptions.csproj" />
    <ProjectReference Include="..\..\..\ASCOM.Utilities\ASCOM.Utilities\ASCOM.Utilities.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <SupportedOSPlatformVersion>10.0.20348.0</SupportedOSPlatformVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&#xD;&#xA;&quot;$(SolutionDir)installercopy.cmd&quot; &quot;$(SolutionDir)&quot; &quot;$(TargetDir)$(TargetName).*&quot;" />
  </Target>
</Project>