<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ASCOM.Simulator</RootNamespace>
    <ApplicationIcon>ASCOM.ico</ApplicationIcon>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>ASCOMDriverTemplate.snk</AssemblyOriginatorKeyFile>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <UseWPF>True</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ASCOM.Com.Components">
      <Version>2.0.9</Version>
    </PackageReference>
    <PackageReference Include="Octokit">
      <Version>14.0.0</Version>
    </PackageReference>
    <PackageReference Include="TaskScheduler">
      <Version>2.12.1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="ASCOM.png" />
    <None Include="ASCOMDriverTemplate.snk" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Content Include="ASCOM.ico" />
    <None Include="Resources\ASCOM.bmp" />
    <Content Include="Resources\simulator.pix">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ASCOM.Attributes\ASCOM.Attributes.csproj">
      <Project>{2c40fad9-de75-4360-a0ad-911c4d24d98c}</Project>
      <Name>ASCOM.Attributes</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\ASCOM.DeviceInterface\ASCOM.DeviceInterface.csproj">
      <Project>{350a73bd-60d1-03e4-2edc-a617d2d79ce3}</Project>
      <Name>ASCOM.DeviceInterface</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\ASCOM.DriverAccess\ASCOM.DriverAccess.csproj">
      <Project>{3b6c23f5-c590-4385-86bb-98b604b565ba}</Project>
      <Name>ASCOM.DriverAccess</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\ASCOM.Exceptions\ASCOM.Exceptions.csproj">
      <Project>{6fd62ea4-8b79-4805-85ec-35178759c405}</Project>
      <Name>ASCOM.Exceptions</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\ASCOM.SettingsProvider\ASCOM.SettingsProvider\ASCOM.SettingsProvider.csproj">
      <Project>{4fffd202-81d4-4549-880b-09b640d72c1d}</Project>
      <Name>ASCOM.SettingsProvider</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\ASCOM.Utilities.Video\ASCOM.Utilities.Video.csproj">
      <Project>{CE1C4CD1-E730-4F08-A839-F181E414E5A0}</Project>
      <Name>ASCOM.Utilities.Video</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\ASCOM.Utilities\ASCOM.Utilities\ASCOM.Utilities.csproj">
      <Project>{7B9B8BE0-9517-0548-11D2-27B6261AB180}</Project>
      <Name>ASCOM.Utilities</Name>
    </ProjectReference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&quot;$(SolutionDir)installercopy.cmd&quot; &quot;$(SolutionDir)&quot; &quot;$(TargetDir)$(TargetName).*&quot;" />
  </Target>

</Project>